# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
# -*- coding: utf-8 -*-
import grpc

import data_interface_pb2 as data__interface__pb2


class ServiceInterfaceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.resident_info = channel.unary_unary(
        '/data_interface.ServiceInterface/resident_info',
        request_serializer=data__interface__pb2.rqb_resident_info.SerializeToString,
        response_deserializer=data__interface__pb2.rqb_resident_info.FromString,
        )
    self.resident_add = channel.unary_unary(
        '/data_interface.ServiceInterface/resident_add',
        request_serializer=data__interface__pb2.rqb_resident_info.SerializeToString,
        response_deserializer=data__interface__pb2.rqb_resident_info.FromString,
        )
    self.family_members = channel.unary_unary(
        '/data_interface.ServiceInterface/family_members',
        request_serializer=data__interface__pb2.rq_resident_id.SerializeToString,
        response_deserializer=data__interface__pb2.rp_family_list.FromString,
        )
    self.resident_ehr_stats = channel.unary_unary(
        '/data_interface.ServiceInterface/resident_ehr_stats',
        request_serializer=data__interface__pb2.rq_resident_id.SerializeToString,
        response_deserializer=data__interface__pb2.rp_list_common.FromString,
        )
    self.service_list = channel.unary_unary(
        '/data_interface.ServiceInterface/service_list',
        request_serializer=data__interface__pb2.rq_service_list.SerializeToString,
        response_deserializer=data__interface__pb2.rp_list_common.FromString,
        )
    self.service_stats = channel.unary_unary(
        '/data_interface.ServiceInterface/service_stats',
        request_serializer=data__interface__pb2.rq_service_stats.SerializeToString,
        response_deserializer=data__interface__pb2.rp_list_common.FromString,
        )
    self.service_detail = channel.unary_unary(
        '/data_interface.ServiceInterface/service_detail',
        request_serializer=data__interface__pb2.rq_record_id.SerializeToString,
        response_deserializer=data__interface__pb2.rb_record_data.FromString,
        )
    self.service_options = channel.unary_unary(
        '/data_interface.ServiceInterface/service_options',
        request_serializer=data__interface__pb2.rq_service_option.SerializeToString,
        response_deserializer=data__interface__pb2.rp_list_common.FromString,
        )
    self.edu_list = channel.unary_unary(
        '/data_interface.ServiceInterface/edu_list',
        request_serializer=data__interface__pb2.rq_edu_option.SerializeToString,
        response_deserializer=data__interface__pb2.rp_list_common.FromString,
        )
    self.service_plan_list = channel.unary_unary(
        '/data_interface.ServiceInterface/service_plan_list',
        request_serializer=data__interface__pb2.rq_service_list.SerializeToString,
        response_deserializer=data__interface__pb2.rp_list_common.FromString,
        )
    self.service_plan_stats = channel.unary_unary(
        '/data_interface.ServiceInterface/service_plan_stats',
        request_serializer=data__interface__pb2.rq_service_stats.SerializeToString,
        response_deserializer=data__interface__pb2.rp_list_common.FromString,
        )
    self.service_plan_days = channel.unary_unary(
        '/data_interface.ServiceInterface/service_plan_days',
        request_serializer=data__interface__pb2.rq_plans_day_list.SerializeToString,
        response_deserializer=data__interface__pb2.rp_list_common.FromString,
        )


class ServiceInterfaceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def resident_info(self, request, context):
    """居民
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def resident_add(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def family_members(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def resident_ehr_stats(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def service_list(self, request, context):
    """服务
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def service_stats(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def service_detail(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def service_options(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def edu_list(self, request, context):
    """健康教育
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def service_plan_list(self, request, context):
    """服务计划
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def service_plan_stats(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def service_plan_days(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ServiceInterfaceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'resident_info': grpc.unary_unary_rpc_method_handler(
          servicer.resident_info,
          request_deserializer=data__interface__pb2.rqb_resident_info.FromString,
          response_serializer=data__interface__pb2.rqb_resident_info.SerializeToString,
      ),
      'resident_add': grpc.unary_unary_rpc_method_handler(
          servicer.resident_add,
          request_deserializer=data__interface__pb2.rqb_resident_info.FromString,
          response_serializer=data__interface__pb2.rqb_resident_info.SerializeToString,
      ),
      'family_members': grpc.unary_unary_rpc_method_handler(
          servicer.family_members,
          request_deserializer=data__interface__pb2.rq_resident_id.FromString,
          response_serializer=data__interface__pb2.rp_family_list.SerializeToString,
      ),
      'resident_ehr_stats': grpc.unary_unary_rpc_method_handler(
          servicer.resident_ehr_stats,
          request_deserializer=data__interface__pb2.rq_resident_id.FromString,
          response_serializer=data__interface__pb2.rp_list_common.SerializeToString,
      ),
      'service_list': grpc.unary_unary_rpc_method_handler(
          servicer.service_list,
          request_deserializer=data__interface__pb2.rq_service_list.FromString,
          response_serializer=data__interface__pb2.rp_list_common.SerializeToString,
      ),
      'service_stats': grpc.unary_unary_rpc_method_handler(
          servicer.service_stats,
          request_deserializer=data__interface__pb2.rq_service_stats.FromString,
          response_serializer=data__interface__pb2.rp_list_common.SerializeToString,
      ),
      'service_detail': grpc.unary_unary_rpc_method_handler(
          servicer.service_detail,
          request_deserializer=data__interface__pb2.rq_record_id.FromString,
          response_serializer=data__interface__pb2.rb_record_data.SerializeToString,
      ),
      'service_options': grpc.unary_unary_rpc_method_handler(
          servicer.service_options,
          request_deserializer=data__interface__pb2.rq_service_option.FromString,
          response_serializer=data__interface__pb2.rp_list_common.SerializeToString,
      ),
      'edu_list': grpc.unary_unary_rpc_method_handler(
          servicer.edu_list,
          request_deserializer=data__interface__pb2.rq_edu_option.FromString,
          response_serializer=data__interface__pb2.rp_list_common.SerializeToString,
      ),
      'service_plan_list': grpc.unary_unary_rpc_method_handler(
          servicer.service_plan_list,
          request_deserializer=data__interface__pb2.rq_service_list.FromString,
          response_serializer=data__interface__pb2.rp_list_common.SerializeToString,
      ),
      'service_plan_stats': grpc.unary_unary_rpc_method_handler(
          servicer.service_plan_stats,
          request_deserializer=data__interface__pb2.rq_service_stats.FromString,
          response_serializer=data__interface__pb2.rp_list_common.SerializeToString,
      ),
      'service_plan_days': grpc.unary_unary_rpc_method_handler(
          servicer.service_plan_days,
          request_deserializer=data__interface__pb2.rq_plans_day_list.FromString,
          response_serializer=data__interface__pb2.rp_list_common.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'data_interface.ServiceInterface', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
